### ISSUE TITLE
How can I test if/how it works ?

### ISSUE THREAD

**Issue by breversa** [microg/NominatimGeocoderBackend#2]
The title says it all… Anyway to test that backend ?

**Comment by mar-v-in** [comment]
The number of apps making use of this feature is rather low, but one of them is the Android Gallery app. If geolocation data is stored with a photo (can be enabled in camera settings), the details page (menu->details) will show the address of the location. Additionally, location is displayed as address when grouping photos by location instead of album.

**Comment by breversa** [comment]
I tested like you said and indeed, it works properly. Thanks !
Is there any way to determine _what_ app uses that backend ?

**Comment by n76** [comment]
I noticed yesterday that the Weather Widget at https://f-droid.org/repository/browse/?fdfilter=weather+widget&fdid=org.jsharkey.sky uses this backend to map ZIP (postal) codes and/or city names to lat/lon and lat/lon to city names.

It would be nice to have a list of apps that use this backend. At present you can check using ADB by running a command like

adb logcat | grep NominatimGeocoderBackend

while you play around with apps that might be using this type of service.

**Comment by ArchangeGabriel** [comment]
A test has been added in UnifiedNlp SelfCheck to verify whether this is working or not. ;) See the referenced link just above my comment.
