### ISSUE TITLE
Offline data base possible ?

### ISSUE THREAD

**Issue by intika** [microg/NominatimGeocoderBackend#5]
Hello :) 

Is it possible to use a sort of offline database ? 

Thanks

**Comment by n76** [comment]
How big or detailed?

I've been mulling over trying to get the Maps.me and/or the OsmAnd projects to either build in a geocoder back end for UnifiedNLP or providing an API so that a geocoder backend could query their downloaded OpenStreetMap data. The databases are pretty big and it seems a shame that everything that uses OSM data has to use up storage for basically redundant data.

Alternatively, at least for the United States, a simple one that just worked off of ZIP (postal) codes and town names could be made that would not have too big a data base and might be a little useful.

In any case, I don't think it should be part of the NominatimGeocoderBackend but rather another backend that could be selected in addition to or instead of this backend.

**Comment by intika** [comment]
it's doable, with OpenWlanMapNlpBackend or OpenBmapNlpBackend  we could download an offline database (1GB)... 
but all non official microg backends (not developed by Marvin) are not working for me... this one is the best and at least i prefer giving my location request to mozilla instead of other company. 

but an offline database would be great.

**Comment by n76** [comment]
My local GSM and/or local WiFi backends don't work for you? If that is true could you post issues for them at either https://github.com/n76/Local-GSM-Backend or https://github.com/n76/wifi_backend

Thanks!

**Comment by intika** [comment]
Thanks for the answer :) and thanks a lot for your packages :+1: 
i will post issue in the appropriated place...
With Local-GSM-Backend : i get battery draining and it does not seems to find the location. (android v4.4.4) 
With wifi_backend : it works but it's not reliable as we have to record all the location first, it's kind a battery draining by concept as it need wifi and gps.
